config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  post '/micro', to:'microposts#create'
  get '/micro',to:'microposts#new'


  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/sign_in' => 'devise/sessions#new'
  end
  
  resources :users
  resources :microposts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many:microposts,dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!,only:[:create,:destroy]
    before_action :correct_user,   only: :destroy

    def show
      @micropost = Micropost.find(params[:id])
      @user = User.find_by(id: @micropost.user_id)

      @microposts=Micropost.all.order(created_at: 'desc')
        
    end

    def new
      @micropost = Micropost.new
    end

    def create
      @micropost = current_user.microposts.build(micropost_params)

        if @micropost.save
          flash[:success] = "Micropost created!"
          redirect_to root_url
        else
          render 'new'
        end
    end

    def destroy
      @micropost.destroy
      flash[:success] = "Micropost deleted"
      redirect_to request.referrer || root_url
    end

    def edit
      @micropost = Micropost.find(params[:id])
    end

    def update
        @micropost = Micropost.find(params[:id])
        if @micropost.update(micropost_params)
            redirect_to root_path
        else
            render 'edit'
        end

    end

    private
  
      def micropost_params
        params.require(:micropost).permit(:title,:content)
      end
      
      def correct_user
        @micropost = current_user.microposts.find_by(id: params[:id])
        redirect_to root_url if @micropost.nil?
      end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      @microposts = current_user.microposts.build
    end
    @microposts=Micropost.all.order(created_at: 'desc')
   

  end

  def show
    @user = User.find(params[:id])
    @micropost = Micropost.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/micropost_helper.rb
module MicropostHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
    <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
 <header>
    <p id="logo"><a href="http://192.168.33.10:3000">Meeting<span>chat</span></a></p>
    <nav>
        <ul>
                       <li><a href="http://192.168.33.10:3000">トップ</a></li>
            <% if user_signed_in? %>
              <li><a href="http://192.168.33.10:3000/micro">新規投稿</a></li>
              <li>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            <% else %>
              <li><a href="http://192.168.33.10:3000/users/sign_up">新規登録</a></li>
              <li><a href="http://192.168.33.10:3000/users/sign_in">ログイン</a></li>

              
            <% end %>
        </ul>
    </nav>
    <div class="clear"></div>
</header>
        <nav>
          <ul class="nav navbar-nav navbar-right">

          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>

    <footer>
    <div id="footer_inner">
        <p>Meetingchat 2020 All Rights Reserved</p>
    </div>
</footer>
  </body>
</html>

app/views/microposts/_index.html.erb
<ul>
<% if @microposts.present?%>
<% @microposts.each do |a|%>
    
    <div>
    
    <h2><%= link_to a.title,micropost_path(a)%></h2>
    <% if user_signed_in? && current_user.id == a.user_id%>
    <%= link_to "削除", a, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <%= link_to "編集",  edit_micropost_path(a) %>                          
    <% end %>
    <%time=a.created_at%>
    <p><%=   time.strftime('%y/%m/%d')%></p>

    </div>
<% end %>
<% end %>
</ul>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <span class="title"><%= micropost.title %></span>
</li>

app/views/microposts/edit.html.erb
<% provide(:title, 'micro') %>
<div class="title">
<h1>編集</h1>
</div>
<%= form_for @micropost, url: micropost_path(@micropost) do |f|%>
<%= render 'shared/error_messages', object: f.object %>

  <div class="titlearea">
  <p>会議の名前</p>
  <%= f.text_field :title, placeholder: "enter title" %>
  </div>

  
  <div class="titlearea">
  <p>会議の内容</p>
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <div class="botan">
  <%= f.submit "Post", class: "btnbtn-primary" %>
  </div>
<% end %>

app/views/microposts/new.html.erb
<% provide(:title, 'micro') %>
<div class="title">
<h1>新規投稿</h1>
</div>


<%= form_for(@micropost) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

  <div class="titlearea">
  <p>会議の名前</p>
  <%= f.text_field :title, placeholder: "enter title" %>
  </div>
  

  <div class="titlearea">
  <p>会議の内容</p>
  <%= f.text_field :content, placeholder: "Compose new micropost..."%>
  </div>
  <div class="botan">
  <%= f.submit "Post", class: "btnbtn-primary" %>
  </div>

<% end %>

app/views/microposts/show.html.erb
<!DOCTYPE html>
<html>
<head lang="ja">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="style.css" type="text/css" media="screen">
</head>
<body>



<div id="title">
    <div>
       
    <%time=@micropost.created_at%>
    <p><%=   time.strftime('%y/%m/%d')%>
    <%=   @user.email%>

    </p>
        <h1><%=@micropost.title %></h1>
        
        <p><%=@micropost.content %></p>
    </div>
</div>



</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
<head lang="ja">
    <meta charset="UTF-8">
    <title>Rails Camp Blog</title>
    <link rel="stylesheet" href="style.scss" type="text/css" media="screen">
</head>

<body>
<div id="main">
<%= link_to image_tag("jonathan-riley-VW8MUbHyxCU-unsplash.jpg", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
</div>


<% if user_signed_in? %>
      <div id="article_wrap">

          <div id="article_list">
            <h3>Meeting </h3>

            <%= render 'microposts/index' %>
            

          </div>
          </div>


            <div id="sidebar">
              
              
          </div>
          <div class="clear"></div>
      </div>
<%else%>
<div class="mae">
  <div class="mae-mae">
  <h1>ようこそ、Meetingchatへ</h1>
  </div>

  <div class="btnbtn">
  <a href="http://192.168.33.10:3000/users/sign_up" class="btn">Sign up</a>
  

  <p>会議の予定を立てよう！</p>
  </div>
</div>

<%end%>



</body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>